<a href="https://colab.research.google.com/github/VadPA/PyTorch/blob/master/Lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# 1. Создайте случайный FloatTensor размера 3x4x5

In [3]:
a = torch.randn(3, 4, 5)
a

tensor([[[-1.6580e+00,  1.0434e+00,  1.2749e-01, -3.9453e-01, -1.0583e+00],
         [-2.1733e+00, -2.4753e-01,  9.0516e-01, -9.4241e-01, -5.1325e-01],
         [ 1.1496e-01,  6.4910e-01,  1.0646e-01, -2.7123e-01, -1.2925e+00],
         [-8.9753e-01,  5.3365e-01,  1.5722e+00, -9.5110e-01, -1.6327e-01]],

        [[-4.2982e-01, -1.1250e+00, -4.6661e-01, -1.3358e+00, -7.7898e-01],
         [-1.6179e+00, -7.1237e-01,  1.5329e+00,  3.1454e-01, -6.4831e-01],
         [ 3.2094e-01,  3.5468e-04, -5.1211e-02, -6.5503e-01,  9.6468e-03],
         [ 1.1852e+00, -4.6562e-01, -4.7667e-01,  9.5779e-01,  4.1249e-01]],

        [[-6.0410e-01, -8.0737e-01, -3.7144e-01, -4.7387e-02, -1.3594e+00],
         [ 5.4463e-01,  8.2581e-01,  4.5122e-01,  6.0565e-01, -1.2856e+00],
         [-3.3716e-01, -7.8600e-01, -2.3709e+00,  3.9062e-01,  4.7636e-01],
         [ 2.0374e-01,  6.2961e-01, -6.0868e-01,  2.3834e+00, -4.4119e-01]]])

# 2. Выведите его форму (shape)

In [4]:
a.shape

torch.Size([3, 4, 5])

# 3. Приведите его к форме 6х10

In [10]:
a.reshape(-1, 10).size()

torch.Size([6, 10])

# 4. Создайте случайный IntTensor размера 10

In [15]:
b = torch.IntTensor(10)
b

tensor([ 109914752,          0,         24,          0,         -1,      32694,
        1668444020, 1767059048, 1529374074,  824192054], dtype=torch.int32)

# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [17]:
a.reshape(-1, 10).mv(b.type(torch.FloatTensor))

tensor([-8.6012e+08,  2.0920e+09,  1.4196e+09,  2.2093e+08,  1.9755e+09,
         3.2193e+09])

# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [18]:
a.reshape(-1, 10).mm(a.reshape(-1, 10).T)

tensor([[11.8847,  6.1968,  5.9470, -4.2963,  0.6785, -4.3909],
        [ 6.1968,  6.6835,  3.8285, -2.8431,  1.4320, -4.5217],
        [ 5.9470,  3.8285, 10.0535, -1.5296,  2.7097,  0.5671],
        [-4.2963, -2.8431, -1.5296,  3.4710, -0.0615,  2.1009],
        [ 0.6785,  1.4320,  2.7097, -0.0615,  6.2067,  3.4197],
        [-4.3909, -4.5217,  0.5671,  2.1009,  3.4197, 13.4155]])

# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [28]:
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

In [29]:
y = x**3 + z - 75*t

In [30]:
y.backward()

In [31]:
x.grad

tensor(3.)

In [32]:
z.grad

tensor(1.)

In [33]:
t.grad

tensor(-75.)

# 8. Создайте единичный тензор размера 5x6

In [34]:
torch.ones(5, 6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

# 9. Переведите его в формат numpy

In [35]:
torch.ones(5, 6).numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)